# Generated by Django 4.2.6 on 2025-07-07 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số dư trước')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số dư sau')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin thực hiện')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log thay đổi số dư',
                'verbose_name_plural': 'Log thay đổi số dư',
                'ordering': ['-created_at'],
            },
        ),
    ]
