# Generated by Django 4.2.6 on 2025-07-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đội')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo đội')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đội bóng',
                'verbose_name_plural': 'Đội bóng',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='Ngày giờ trận đấu')),
                ('home_score', models.IntegerField(default=0, verbose_name='Tỷ số đội nhà')),
                ('away_score', models.IntegerField(default=0, verbose_name='Tỷ số đội khách')),
                ('status', models.CharField(choices=[('upcoming', 'Sắp diễn ra'), ('live', 'Đang diễn ra'), ('finished', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='upcoming', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='bongda.team', verbose_name='Đội khách')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='bongda.team', verbose_name='Đội nhà')),
            ],
            options={
                'verbose_name': 'Trận đấu',
                'verbose_name_plural': 'Trận đấu',
                'ordering': ['-match_date'],
            },
        ),
    ]
