# Generated by Django 4.2.6 on 2025-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LodeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Số lô đề')),
                ('frequency', models.IntegerField(default=0, verbose_name='Tần suất xuất hiện')),
                ('last_appearance', models.DateField(blank=True, null=True, verbose_name='Lần xuất hiện cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Số lô đề',
                'verbose_name_plural': 'Số lô đề',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LodeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày xổ số')),
                ('region', models.CharField(choices=[('mien_bac', 'Miền Bắc'), ('mien_trung', 'Miền Trung'), ('mien_nam', 'Miền Nam')], default='mien_bac', max_length=20, verbose_name='Miền')),
                ('numbers', models.JSONField(verbose_name='Các số kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Kết quả lô đề',
                'verbose_name_plural': 'Kết quả lô đề',
                'ordering': ['-date'],
                'unique_together': {('date', 'region')},
            },
        ),
    ]
