# Generated by Django 4.2.6 on 2025-07-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50, verbose_name='Số cược')),
                ('bet_type', models.CharField(choices=[('bao_lo', 'Bao Lô'), ('de_dau', 'Đề Đầu'), ('de_db', 'Đề Đặc Biệt'), ('xien_2', 'Xiên 2'), ('xien_3', 'Xiên 3'), ('xien_4', 'Xiên 4')], max_length=10, verbose_name='Kiểu cược')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền cược')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
    ]
